# Fake out Travis CI, since PHP isn't supported when using their Docker services
language: php

env:
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

script: phpunit test/ContainerTest.php
